version: '3.3'
services:
  edgeware:
    image: edgeware:latest
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "2"
    volumes:
      - ./data_edgeware:/data/chains
    ports:
      - "127.0.0.1:9933:9933"
      - "127.0.0.1:9944:9944"
      - "127.0.0.1:30333:30333"
    command: ['--dev', '--ws-external', '--rpc-external', '--rpc-cors', 'all', '--rpc-methods=Unsafe']
